### ISSUE TITLE
HW2 void unarchive(char* archivefile)

### ISSUE THREAD

**Issue by doug-skinner** [doug-skinner/csi_402_systems_programming#2]

**Comment by SherriLewis** [comment]
back again. Have a quick question on this function. So am I too assume that for this we just need to read the archive file and then write the files from the archive?  Ummmm, if that's the case, where do we write them too? I'm a little confused on what to do here. Do we write them to the directory that we start in?  LOL I'm scratching my head a bit on this.  I'll be here on and off all night. Just gotta break for dinner at 6.

**Comment by doug-skinner** [comment]
Yes, we'll be writing the files to whatever directory we get called from. So we just open a new file with the name that we pull out of the archive, and then dump the contents into it.

**Comment by SherriLewis** [comment]
Ok I did this in about 30 minutes while being distracted by a movie LOL
Take a look and see if this is on track. I wasn't sure if I could use a variable after getting the current working directory. I tried to incorporate it into the fopen.  Hopefully I'm not off by much on the code part. It would be nice if it didn't take me hours just to write one small function!!!
[unpack.zip](https://github.com/doug-skinner/csi_402_systems_programming/files/1425486/unpack.zip)

**Comment by SherriLewis** [comment]
BTW what happened to our other partner? Did he drop the class?

**Comment by doug-skinner** [comment]
definitely looks like you're on the right track. although rather than starting after the number of files I would recommend reading in the number of files, and then using that as a loop counter to know how many structs you have to process

**Comment by doug-skinner** [comment]
and I don't know, I haven't seen him so I assumed so

**Comment by SherriLewis** [comment]
I  used a few lines of code to get the number and put it in buffer and then used that in the loop but I'll agree that my way was a bit odd. I used two steps but I'll try a rewrite for easier reading.
