### ISSUE TITLE
HW2 A function to handle the -l flag.

### ISSUE THREAD

**Issue by doug-skinner** [doug-skinner/csi_402_systems_programming#3]

**Comment by SherriLewis** [comment]
archiver -l archivename: Print to stdout the total size of the archive, the number of files
in the archive, and each filename along with the corresponding file size (one file name and
size per line)


I assume the size can be done with the fseek and ftell commands for the file size?
The number of files can be done by  Looking at the first 4 bytes of the archive file?
and I assume we can get the filenames from the argv input by using a loop to count the number of files that are defined on input?

**Comment by doug-skinner** [comment]
Yes for the first two. For the last one, the file names, we are going to have to loop through the entire file to read the filenames as the only input we're given is the archive filename.

**Comment by SherriLewis** [comment]
OK That's what I thought but I wasn't sure. I'm back from dinner now so I'll be spending a bit of time on this and I'll send you what I have for this function. I'm sure it's got to be adjusted but feel free to give suggestions or help if you like.

**Comment by SherriLewis** [comment]
void archiveDetails( File *archive){
// Open file and error check
 archive = fopen(archive, "r");
 
      if (archive == NULL)
        printf(" unable to open file \n ");


        // Get total size of the file
      fseek(archive, 0, SEEK_END);
    long size = ftell(archive);
    rewind(archive);
    printf("The size of this archive file is \%d\n", size);

 // get the value for the filesize
working on this now. Unfortunately it's a slow process for me with the syntax

**Comment by SherriLewis** [comment]
Do I have to read the contents into a buffer first and then print or is that more than what I need to do?

**Comment by SherriLewis** [comment]
A little more in this one. I just want to get the last part done and then I'll be going to do other work. My eyes are getting crazed from this computer. I'll try to get the last part before I go to bed. I'm sure there are mistakes but I"m hoping I'm on the right track.
[L_Flag.zip](https://github.com/doug-skinner/csi_402_systems_programming/files/1409196/L_Flag.zip)

**Comment by doug-skinner** [comment]
This looks good, however I would recommend passing the file name as a char array instead of the file pointer. like so:

```
void list(char *filename) {
    FILE *fp;
    fp = fopen(filename, "r");
    // The rest of you code
}
```

**Comment by SherriLewis** [comment]
OK sounds good. I just got back to Trying to get the rest of the function started. So I assume that I can set the start at the 4 byte mark which is directly after the number of files. Then from there it appears that the length of the filename is in 1 byte and then the name itself is also 1 byte based on the fact that the name can be up to 1 byte and n1 = l1 + 1? Then we have 4 bytes for the s1, but how do I start all over at the necessary block when the files can be different sizes? The offset would always change if the files were different sizes right?

**Comment by doug-skinner** [comment]
Yes, that's correct. So what you do is you just read in a buffer and then see what you can do with it. Meaning that you know the length of the contents come first. So you read in a chunk of data into a buffer, and then look for a number. then use that number as the number of bytes to read in for the contents.

**Comment by SherriLewis** [comment]
A light bulb may have just gone off. Are we using a struct in this assignment? If we used a struct with the filename length, filename , etc wouldn't we be able to loop through the archive using that to get to the same location of each filename and then put the contents into an char array (or something like that) to print out each filename?

**Comment by doug-skinner** [comment]
Yes, a struct would be very helpful with this

**Comment by SherriLewis** [comment]
If only I was better at C syntax LOL......I'm beating my head against a wall. Understanding the logic is great but writing the code for me sucks!  I haven't looked at your code at all because I want to try it on my own. Just a really slow process. I'll see if I can get this part completed tonight but if not I take a stab at it again tomorrow. Going to go fry my brain now :-)

**Comment by SherriLewis** [comment]
So I went through the documents for this assignment and it doesn't appear that this function  has any specific given rules. I'm having a harder time working with the archive file so why can't we get the filenames from the initial input? It would seem rather easy to just make an array of filenames based on the argument values given?  I'll be back later this evening working on this again. Just wanted to check in with you

**Comment by doug-skinner** [comment]
The function will be called like this: 
```
archiver -l archivename
```

on the very top of page two

**Comment by SherriLewis** [comment]
yeah, I just looked at it. So basically I'm screwed :-) 
I know what I want to do, just can't figure out what code to use to do it.  I know we can set the file to start after the number of files, and then we can guarantee that the next value will be one byte, but I can't figure out how to get value from the filename size and then read that many characters. 

Just have to focus a bit.  I'll be back

**Comment by SherriLewis** [comment]
Trying to get the right struct

typedef struct Archive
{
    unsigned int FileNameLength;
    unsigned char FileName;
} archive;

how can I add the contents of the file to the struct if it can always be a different size?

**Comment by SherriLewis** [comment]
Back again. I'm trying to bounce around between my classwork so I decided to go back to this again. I apologize for not being very much help. Unfortunately I think this would be easier if we were able to communicate better but I know that your job and mine as well make that difficult, not to mention I'm not even in the country.

**Comment by doug-skinner** [comment]
Hey, I'm so sorry. I'm actually currently at work, and its been a stressful week full of server crashes and calc tests. I'll be finishing this over the next couple days and will look at your messages in a few minutes

**Comment by SherriLewis** [comment]
No problem. I get it. I'm going to be working to try and help out over the next few days as well. Unfortunately I can't connect to the ualbany server through my Cisco anyconnect vpn so the best I can do is send code that I hope will be fairly usable. I can only assume the issue is because of where I am but I'll have my husband take a look at it later and maybe he can spot something.  I'll be sending some stuff later. Hopefully it will be semi complete for the functions that we need.  Hopefully!

**Comment by SherriLewis** [comment]
Take a look at this. I tried to use the struct that you had created but I'm not sure the last part of the function is correct. That's the part where we need the names and the size printed. I'm starting to understand most of it but some of it is still a bit hazy.  I have full internet for the rest of the cruise so I'm doing lots of searching for
[L_Flag.zip](https://github.com/doug-skinner/csi_402_systems_programming/files/1423210/L_Flag.zip)
 help so don't feel bad if you can't respond right away.

**Comment by doug-skinner** [comment]
That's definitely on the right track. If you look at mine, I just updated and provided working unarchive and list functions. They'll be cleaned up at some point, but they are working.

**Comment by SherriLewis** [comment]
LOL, nope, I'm not gonna look at them just yet. I'm going to try and see what I can do for the other functions that you had listed and then I'll take a look. I need to try and work through as much as possible without constant help. It's a slow process for me but I think once I get it or see the correct code I'll store it in my memory for future use.....like the final!  I'm kinda scared to see the midterm after reading what he said in the new slides.

**Comment by doug-skinner** [comment]
That makes sense, that is the best way to learn. Your L function is almost what I did, if that does help.

**Comment by SherriLewis** [comment]
Well that makes me feel better because I was thinking that it was probably going to be really basic compared to your function!! I do have to admit that I'm googling all kinds of examples to see how to do parts of the necessary code. I'm fairly sure in the end I'll know something about how to handle a binary file.

**Comment by doug-skinner** [comment]
oh you definitely will. I honestly never really knew the applications of binary files before this project
